### ISSUE TITLE
Subregion maps to table

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere#112]
In the front page, we have a map divided by subregions.
Ideally, this should work for the user:
1. You select a region
2. It returns all entries located in the countries of that region

for the coder:
there should be a table where subregions have their own column, filled with the countries of that subregion. The code would:
1. [Input subregion by user] -> look for subregion in column header
2. Go through the countries listed in that column
3. Return entries of located in those countries

To do this. We need to:
- [ ] Set up subregion table. @cube5, what format should it be? CSV, json?
- [ ] Create the code to do this function

Also, we may need to address the decision for using these regions. We should look for standarized map subregions that take into account geography, politics, and culture

**Comment by sabgaby** [comment]
This feature was scraped!
