### ISSUE TITLE
Add other field entries in the infobox?

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere#117]
Are there any other field entries we would like to put in the infobox? For inspiration we can look at the [infobox for Genspace in Wikipedia](https://en.wikipedia.org/w/index.php?title=Genspace&action=edit)

Some ideas can be:
- motto
- predecessor
- merged
- successor
- formation
- extinction
- purpose
- headquarters
- services
- membership
- language
- leader title and name
- key people
- budget

**Comment by sabgaby** [comment]
For now, we have settled on the basic variables needed:
- Title
- Subtitle
- Start-Date
- End-Date
- Type
- Location (address/city/country)
- Website/External link
If applicable or very much recommended
- Host-org
- Call-to-action

---
* These names may change
