### ISSUE TITLE
Adjust design for table view

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere#121]
Change the design of the table view. Something like this?
Like having a sort and filter.. advanced table into this place. 

![screen shot 2016-07-13 at 14 57 00](https://cloud.githubusercontent.com/assets/18292357/16804881/159bb582-490e-11e6-8488-70b314e370ee.png)

**Comment by sabgaby** [comment]
The design for the list of entries has changed to something like this. Still needs to be implemented
![screen shot 2016-10-25 at 13 55 02](https://cloud.githubusercontent.com/assets/5911330/19685027/b1fc869c-9aba-11e6-9af7-b6050e5dd874.png)
![screen shot 2016-10-25 at 13 55 13](https://cloud.githubusercontent.com/assets/5911330/19685026/b1f7a366-9aba-11e6-86c9-35136657369a.png)
