### ISSUE TITLE
Downloading Dataset

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere#139]
We need a way for individuals interested in the dataset to be able to download it. I think it would be a nice idea if we link the Release to the Dataset so that we know how many get downloaded.

I think we should keep the same Release for just adding data. I am not sure how this works but 
Travis has some kind of way to [deploy releases](https://docs.travis-ci.com/user/deployment/releases). We should check that out

**Comment by ahuacatl** [comment]
Here is a nice [article](http://blog.okfn.org/2013/07/02/git-and-github-for-data/) by the okfn on using git and github for data

**Comment by sabgaby** [comment]
in the data folder there is now a json file that can easily be downloaded
