### ISSUE TITLE
Fixing the "No GitHub API authentication could be found" when jekyll serve

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere#140]
`GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data`
I keep getting this warning on my terminal
![screen shot 2016-09-12 at 10 38 34](https://cloud.githubusercontent.com/assets/18292357/18429715/3fa7f056-78d5-11e6-9ab3-7d46163775b7.png)

It should be fixed, [this is a possible answer](http://mycyberuniverse.com/web/fixing-jekyll-github-metadata-warning.html)

**Comment by fgreve** [comment]
Add `github: [metadata] `
at the end of `_config.yml`
*from [here](https://github.com/github/pages-gem/issues/399)

**Comment by sabgaby** [comment]
Thanks @fgreve 
all I did was add 
`github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
`
to the config file. The link says to add github-pages gem, but since jekyll 2.5 this is not necessary
