### ISSUE TITLE
RSS feed from changes to specific files

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere#146]
I don't know if this is possible. But I think it would be nice if managers could subscribe, or watch, to an RSS feed of their entries and follow if any contributor has made any pull requests with changes to that file. 
[here](http://stackoverflow.com/questions/9732779/how-to-watch-only-a-directory-in-a-github-repository) they give some possible solutions

**Comment by sabgaby** [comment]
it should look something like:
https://github.com/DIYbiosphere/sphere/commits/master/_projects/DIYbiosphere.md.atom
 then just add it to an RSS feeder
