### ISSUE TITLE
Notice of copyright infringement

### ISSUE THREAD

**Issue by Juul** [DIYbiosphere/sphere#161]
It looks like text and logo which are licensed under CC BY-SA 4.0 is being relicensed under CC Zero here: http://sphere.diybio.org/entries/labs/CounterCultureLabs

as well as on the map here: http://sphere.diybio.org/maps/

Also, it seems odd that you would pick a wikipedia-incompatible license for this project?

**Comment by sabgaby** [comment]
what license is wikipedia-incompatible? For the text in the entry it says at the bottom: text taken from the initiative's website, i.e. BY, but true, I should have specified SA. In the Terms of Use and Contributor terms, there are specificiations that state that logos and content that links outside of the sphere.diybio.org domain are not considered to fall under our own copyright but to their own.

**Comment by Juul** [comment]
Thanks for the fast reply. The Share-Alike clause means that you cannot mix this content with non-Share-Alike licensed works, even it you explicitly specify the various licenses for the different parts of the work. The SA licenses only give you permission to re-use SA-licensed works only if your resulting derivative work is also SA licensed. This is also why the CC Zero license is wikipedia-incompatible.

**Comment by Juul** [comment]
I should state that I am not trying to be difficult. I am simply showing you a problem that would be much harder to fix later in the project since you would need permission from all contributors to change the project and content license.

**Comment by jasonbobe** [comment]
I thought that was only true for derivative works, not collective works?

http://opendata.stackexchange.com/questions/5378/can-i-put-a-cc-by-sa-photo-in-a-non-cc-by-sa-work/5380#5380

**Comment by Juul** [comment]
Well whaddaya know. I learned something useful today. Thanks! I did not realize the CC license made that distinction. Issue closed.

**Comment by jasonbobe** [comment]
Phew, I honestly thought I may have misunderstood (my default mode really)
something here. I'm only inserting myself here bc I think I might have been
the one who recommended cc0 (also one of my default settings) to Gabriela.

But you are right to have caution on this stuff which can be complicated,
and have unsavory downstream consequences!  I'm open to be educated on
proper approaches :)

**Comment by Juul** [comment]
Oh, the reason I missed it is because similar language is not present in the 4.0 license. I'll ask a hacker lawyer next time I see him whether the same is likely to apply to version 4.0 but I'm assuming they didn't drastically change the intention of the license between versions even if their intention has become more obscure to the layman.

**Comment by jasonbobe** [comment]
This is helpful:
https://twitter.com/wilbanks/status/849259493552795649
