### ISSUE TITLE
orbiting/cms-draft: markdown editor that saves as github commits

### ISSUE THREAD

**Issue by 100ideas** [DIYbiosphere/sphere#163]
The existing content creation/edit workflow is technical and involves a lot of steps (login to github, navigate to correct file, edit in github's text editor, save commit, go back to diybiosphere).

Thomas Preusse's cms-draft ([orbiting/cms-draft](https://github.com/orbiting/cms-draft)) project could be a great starting point for a better editing frontend. It's a javascript content editor (based on react/draft.js) that is capable of directly committing to a github repo.

Users would still need github accounts (I think we could use the same js library used in cms-draft to automate adding github accounts to the diybiosphere repo or opening pull requests), but this could go a long way to simplifying content creation while staying true to the git backend.

- Thomas' [overview article](https://medium.com/project-r/an-article-cms-prototype-6a01a31bce3d)
- [source code](https://github.com/orbiting/cms-draft) repo
- preview gif:

![1-e6axncjfx9qtc_pc2eqn4q](https://user-images.githubusercontent.com/57006/27713396-55f2e006-5ce0-11e7-9f5f-b379e7937870.gif)

**Comment by 100ideas** [comment]
[Prose.io](http://prose.io/#about) ([repo](https://github.com/prose/prose)) is similar, but older (works with jekyll directly?)

> "Prose provides a beautifully simple content authoring environment for CMS-free websites. It's a web-based interface for managing content on GitHub. Use it to create, edit, and delete files, and save your changes directly to GitHub. Host your website on GitHub Pages for free, or set up your own GitHub webhook server."

**Comment by 100ideas** [comment]
Another static site frontend editor / cms <-> github backend: https://www.netlifycms.org/docs/test-drive/

**Comment by sabgaby** [comment]
These are good! I had also looked into frontend editors. The most popular is CloudCannon, not free though.

The only issue I see is that they only preview the markdown. Any added features, or the actual look of the page is not viewable. I don't know if we could also figure out a way for it to build just the edited page so the preview is as it would be. Is it possible? Maybe through Heroku or something similar?

**Comment by sabgaby** [comment]
From plugins there is [pagoda](https://github.com/alagu/pagoda/) which can be run on Heroku.
And Jekyll-Admin

Another good option might be [SiteLeaf](https://www.siteleaf.com/)

**Comment by 100ideas** [comment]
closing since it's so old - will revisit
