### ISSUE TITLE
Authentication via Github

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#179]
With authentification we can create a nicer UI to edit, and to comment and discuss

[repo](https://github.com/prose/gatekeeper)

[blog tutorial](https://makerlog.org/posts/gatekeeper-for-authenticating-with-github)

[Use with Jekyll](https://github.com/prose/gatekeeper/issues/20)

imitate [jkan](https://github.com/timwis/jkan)

**Comment by 100ideas** [comment]
closing since it's so old - will revisit
