### ISSUE TITLE
Avocado Lab test rendering broken

### ISSUE THREAD

**Issue by jasonbobe** [DIYbiosphere/sphere#192]
In the contributing guide, links to test file Avocado Lab and a test rendering. The test rendering link is broken

**Comment by sabgaby** [comment]
Ughh.. My local serve is able to render these links... 
For some reason if the link is:

`/projects/AvocadoLab/AvocadoLab/` it doesn't render it in the push. It should be `/projects/AvocadoLab/AvocadoLab`

will fix this in next commit

**Comment by sabgaby** [comment]
Fixed with 68258b344f4e4141cd80ef55292520689481b856
