### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by xinemata** [DIYbiosphere/sphere#208]
Hello DIYbiosphere community! I'm an artist, educator, and organizer based in LA. I've recently started to experiment with cooking gelatin-based and algae-based bioplastic. It's been a lot of fun and now I'm trying to 3D print the bioplastic I've been creating. I look forward to learn and share my findings with you all!

**Comment by sabgaby** [comment]
Welcome! We appreciate your interest! Sorry for the late reply!!
