### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by hackolite** [DIYbiosphere/sphere#210]
## !!DELETE THIS TEMPLATE AFTER READING
Before submitting an Issue
- **Avoid making duplicates**: You can :+1: vote for an existing issue
- **Organize new issues**: Members should organize tickets and apply labels

Follow steps of each type of issue
- [ ] **request to be a member** _title:_ 'Membership request'. _description:_ a bit about yourself (optional)
- [ ] **report error/problem in an webpage** _title:_ name of webpage _description:_ describe the problem, or error and what it should be instead.
- [ ] **report broken link** _title:_ 'Broken link'. _description:_ where you encountered the broken link
- [ ] **report a bug** _description:_ describe the problem, how you encountered it and what you expected instead. Provide screenshots and screencaptures if possible
- [ ] **make a suggestion** _description:_ describe your idea, how it should work and look like. Provide examples and references.
- [ ] **ask a question** _title:_ include a '?'. Or ask questions in Gitter, or Slack, you can directly message users in either. Check our FAQs too.

**Comment by hackolite** [comment]
broken link : http://sphere.diybio.org/projects/DIYbiosphere/

**Comment by sabgaby** [comment]
Thanks @hackolite for reporting this! I think you mean there was a broken link in the index page, from the DIYbiosphere button of [Learn More].. It is now fixed!
