### ISSUE TITLE
Broken link - Avocado example page

### ISSUE THREAD

**Issue by sctv** [DIYbiosphere/sphere#213]
[AvocardoLab](http://sphere.diybio.org/docs/tutorials/AvocadoLab/) link is broken from [add-entry](http://sphere.diybio.org/docs/tutorials/add-entry/) page. 

Reference:
(https://github.com/diybiosphere/sphere/blob/master/docs/tutorials/add-entry.md) 
> Good reference materials are the Writing Guide and the example entry of the [Avocado Lab](http://sphere.diybio.org/docs/tutorials/AvocadoLab/) webpage which is rendered from this file

**Comment by sabgaby** [comment]
Hey thanks @sctv for reporting this! I fixed the broken link now! 😄

**Comment by sctv** [comment]
Thanks.
