### ISSUE TITLE
Membership Request

### ISSUE THREAD

**Issue by ThatMrE** [DIYbiosphere/sphere#215]
Description:

Elliot Roth is the founder of Spira, a company that creates microalgae technology. After being trained as a University Innovation Fellow at the Stanford d.School, he started multiple entrepreneurial projects including the DIYbio lab Indie Lab, and a number of science startups, through which he has raised over $300,000. He has worked to catalyze community science labs in the Virginia area, and is working on starting his second lab in DC. Elliot graduated Virginia Commonwealth University with a degree in Biomedical Engineering; he spent five years consulting in product design and business strategy before starting Spira. He is a Kairos Fellow, a Seasteading Ambassador, and sits on the Virginia Governor’s Council for Youth Entrepreneurship. Elliot has spoken at Synbiobeta, SXSW, and Thought for Food on social impact, synthetic biology and food. Spira was chosen for the RebelBio, Lighthouse Labs, and the World Food Programme accelerator programs, and is the winner of the CommBeBiz award and Halcyon Fellowship. Spira is now starting at the BeGreen Hub and is a member of the inaugural cohort of the NSF I-Corps program AccelerateDC. He is incredibly motivated to solve physiological needs using simple biological design.

**Comment by sabgaby** [comment]
![screen shot 2018-03-20 at 10 04 02](https://user-images.githubusercontent.com/5911330/37645071-0ee1ebce-2c26-11e8-9625-91879ae0d23b.png)
Awesome to have you Elliot! Invitation link sent!
