### ISSUE TITLE
New Contributor- MaryHBW of Counter Culture Labs

### ISSUE THREAD

**Issue by maryhbw** [DIYbiosphere/sphere#216]
## !!DELETE THIS TEMPLATE AFTER READING
Before submitting an Issue
- **Avoid making duplicates**: You can :+1: vote for an existing issue
- **Organize new issues**: Members should organize tickets and apply labels

Follow steps of each type of issue
- [ ] **request to be a member** _title:_ 'Membership request'. _description:_ a bit about yourself (optional)
- [ ] **report error/problem in an webpage** _title:_ name of webpage _description:_ describe the problem, or error and what it should be instead.
- [ ] **report broken link** _title:_ 'Broken link'. _description:_ where you encountered the broken link
- [ ] **report a bug** _description:_ describe the problem, how you encountered it and what you expected instead. Provide screenshots and screencaptures if possible
- [ ] **make a suggestion** _description:_ describe your idea, how it should work and look like. Provide examples and references.
- [ ] **ask a question** _title:_ include a '?'. Or ask questions in Gitter, or Slack, you can directly message users in either. Check our FAQs too.

**Comment by sabgaby** [comment]
Hi @maryhbw! I just sent you an invitation! great to have you
