### ISSUE TITLE
funky carousel

### ISSUE THREAD

**Issue by jasonbobe** [DIYbiosphere/sphere#237]
at least in my browser (chrome on mac), the carousel on the main page is funky. Looks like it might be missing one of the photos? not sure. I can grab a screenshot if the bug doesn't reproduce on your machine. @100ideas

**Comment by 100ideas** [comment]
problem was broken link to offsite image.

logic that selects where images are loaded from is here: https://github.com/DIYbiosphere/sphere/blob/master/index.html#L30

the carousel logic works most reliably if a contribution:
- includes the "promotions" field in yaml frontmatter
- "promotions" DOES NOT include 'image' field link to off-site image

do this:
- just put header.jpg and logo.jpg in the folder with the markdown file [like this](https://github.com/DIYbiosphere/sphere/tree/7fd113c4d526a33ecdc89740ec8aa14a42cb099f/_events/BBKOpenScience)
- jekyll finds the sibling header/logo file if it is named `header.<jpg|png|svg>` or `logo.<jpg|png|svg>` as above and associates it with the yaml when the site is built

not like this:   
- don't add a logo entry to the yaml frontmatter of the md file
- https://github.com/DIYbiosphere/sphere/commit/57192515da6ec14247c7f4c3739fec386f64d112#diff-67da456c47233c206f18df87b5417d3d
