### ISSUE TITLE
request to be a member

### ISSUE THREAD

**Issue by adriangenetics** [DIYbiosphere/sphere#249]
I would like my lab OttawaBioScience www.specyal.com added to the global map of labs. We also use meetup: https://www.meetup.com/Ottawa-Bio-Science/

I would like my account to be added to the diybiosphere too. Information about me can be found under www.specyal.com/adrian.html

Thank you,
Adrian

**Comment by sabgaby** [comment]
Hey Adrian! Welcome!

**Comment by sabgaby** [comment]
@adriangenetics, if you want to add your lab to the global map, make sure to add geopoints to the front matter as such:
```
_geoloc:
  lat: 34.1324
  lng: 651.8903
```
