### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by sjamesparsonsjr** [DIYbiosphere/sphere#253]
Hello, my name is S James Parsons Jr.  I live in Philadelphia and I'm a biomedical engineer focusing on bringing biotech to the home.  I'm working on a startup that focuses on consumer-grade laboratory equipment.

I was at Bio Summit over the weekend, and I feel all of the attendees, their websites, efforts, projects should be indexed on DIYbiosphere.  So, I thought I should help them and contribute to their information, icons, and headers.  

I'd also like to be a DIYbiosphere ambassador for when I go to these conferences/events.  I could share the site, add groups/startups/members/experiments to the site and expose more to DIYbiosphere.

**Comment by jasonbobe** [comment]
YES!!!

**Comment by sjamesparsonsjr** [comment]
Thanks, Jason,  I think I'll start by uploading logo and header artwork for everyone who is already in Biosphere.  So I guess I need to be a Core Developer to have upload access?

**Comment by jasonbobe** [comment]
I added @sjamesparsonsjr as an editor 

cc @sabgaby @100ideas
