### ISSUE TITLE
Problem adding lab

### ISSUE THREAD

**Issue by adriangenetics** [DIYbiosphere/sphere#254]
Hi,

I added the OttawaBioScience lab by following the help instructions. It was added in the master.
I also deleted the bogus MyLab entry.

It's been a day and the web site does not reflect the changes so either there is something wrong with the changes of the build system.

Thank you,
Adrian

**Comment by 100ideas** [comment]
Hi @adriangenetics, thanks for reporting this. we are tackling it in a related issue #256... should be fixed now

**Comment by 100ideas** [comment]
(I got it working in staging https://5da9a308257db3000750016d--diybiosphere.netlify.com/labs/ottawabioscience/)
