### ISSUE TITLE
Create a DOI

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#26]
![screen shot 2016-05-11 at 11 34 55](https://cloud.githubusercontent.com/assets/5911330/15176711/b5684e28-176c-11e6-94e0-6d8da512ed5a.png)

We can create a DOI so that the project is citable. However, we need

**Comment by cube5** [comment]
For sure! :ok_hand:  can we create the release on the next commit? so we can upload it to zenodo
please let me know any thoughts

**Comment by sabgaby** [comment]
After we create the DOI, we should attach it to our [DataReusePlan.txt](https://github.com/DIYbiosphere/diybiosphere.io/blob/master/DataReusePlan.txt) file

**Comment by 100ideas** [comment]
closing since it's so old
