### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by TH7-0421** [DIYbiosphere/sphere#277]
## !!DELETE THIS TEMPLATE AFTER READING
Before submitting an Issue
- **Avoid making duplicates**: You can :+1: vote for an existing issue
- **Organize new issues**: Members should organize tickets and apply labels

Follow steps of each type of issue
- [x] **request to be a member** _title:_ 'Membership request'. _description:_ a bit about yourself (optional)
- [x] **report error/problem in an webpage** _title:_ name of webpage _description:_ describe the problem, or error and what it should be instead.
- [x] **report broken link** _title:_ 'Broken link'. _description:_ where you encountered the broken link
- [x] **report a bug** _description:_ describe the problem, how you encountered it and what you expected instead. Provide screenshots and screencaptures if possible
- [x] **make a suggestion** _description:_ describe your idea, how it should work and look like. Provide examples and references.
- [x] **ask a question** _title:_ include a '?'. Or ask questions in Gitter, or Slack, you can directly message users in either. Check our FAQs too.

**Comment by danwchan** [comment]
Hi this issue is just the template. Please reopen an issue if there is something you wanted to bring up.
