### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by danwchan** [DIYbiosphere/sphere#285]
Hello @jasonbobe @100ideas and @sabgaby 

I'd like to be a member to help out the work you guys have initiated on sphere.DIYbio.org

My name is Danny and I am the new President of the lab Biotech Without Borders. Along with members/leadership from a handful of North American biolabs we identified that sphere.DIYbio.org is a valuable piece of infrastructure for the global DIYbio community. We want it to be an up-to-date portal for individuals and groups around the world to connect just as you articulated on "Our Philosophy" page.

We've noticed a bunch of commits/issues that have accumulated, seen that the website has not been updated in some time, and want to help out. There is a small team of people enthusiastic about the project. I am reaching out to be a member so we can start updating the site. If you'd like to speak to the group let me know and we can schedule a time.

Hope you're keeping well.

**Comment by jasonbobe** [comment]
Would love to have your help, Danny!

**Comment by jasonbobe** [comment]
Sure thing. Will do tomorrow

**Comment by jasonbobe** [comment]
Danny - I just sent you an invitation to diybiosphere via github...

**Comment by danwchan** [comment]
I don't see any invite. Perhaps you must resend? I checked the pull requests and I don't have write access yet.

**Comment by jasonbobe** [comment]
[image: Invite.png]
maybe somewhere in your github profile there is a pending invite?

**Comment by danwchan** [comment]
Hmm I don't see it anywhere. I also don't see the image you attached to the last reply. I looked at the docs a little and they mentioned that if your organization requires 2FA then I have to have that enabled before I can accept an invite. My account was not set up with that feature but I just added it, but I don't see the invite still. Perhaps resend now?

Here's the [doc page](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/inviting-users-to-join-your-organization) I was looking at in case something there clarifies something on your end.

**Comment by danwchan** [comment]
Hi, this is a little embarrassing. I did a through cleaning out of my email for the end of the year and I found the invite to the group in my spam. It's expired now. Fixed my filter settings. Could you please resend.

**Comment by jasonbobe** [comment]
OK, glad to hear, i was getting worried! OK, I resent the invite!

**Comment by danwchan** [comment]
Alright thank you I'm added to the organization now! Please let me know if you have anything you want to bring to the other community biolabs who are interested in the website. I'm excited to start updating the site now and determining the best way to manage it moving forward. Also Happy New Years :D

**Comment by jasonbobe** [comment]
i'm tagging @sjamesparsonsjr who made significant contributions around updating a subset of entries. He may have some advice to share on getting started on your journey of updating the entries for the biolabs. This is critically important work! Let me know if you have questions. Thank you!

**Comment by danwchan** [comment]
Perfect yes I read the exchange on issue #273 and issue #256 that outlines a place for further development. Happy to work with @sjamesparsonsjr on elements of the website.

Besides resolving the currently opened issues I think the group of community labs who I'm representing at the moment are interested in making some sort of submission form to streamline the process. But we will see how far that initiative goes, right now I think the github issues are a great place to organize our work/collaborations. Thanks for being responsive and I will for sure reach out if we have any other questions.

**Comment by sjamesparsonsjr** [comment]
Hi @danwchan, great to have you aboard.   I just sent you an email
