### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by Decentricity** [DIYbiosphere/sphere#288]
Hi! I'm the initiator of [Degenics.com](http://degenics.com), a platform that allows DLT-based anonymous genetic testing & data trading, and we're really interested in joining the DIYBio community, assisting the ecosystem, and getting listed on sphere.diybio.org. I'm the CIO of Blocksphere, a development company based in Indonesia.

You can go ahead and try out our demo at [demo.degenics.com](http://demo.degenics.com) or go to [github.com/Degenics](http://github.com/Degenics) to find more info. If you'd like to contact me via email, you can send it to [p@degenics.com](mailto:p@degenics.com).

**Comment by sjamesparsonsjr** [comment]
Hello, I just sent you an email

**Comment by Decentricity** [comment]
Thanks James! I've responded -- and also filled out the form.

**Comment by Decentricity** [comment]
> Hello, I just sent you an email

Hey James, sent you an email again -- any issues on the form? Need my help to provide anything else?

**Comment by danwchan** [comment]
To my knowledge, the form is taking some time to troubleshoot. If you are able to create your page using [this guide](https://sphere.diybio.org/docs/tutorials/add-entry/) and create a pull request I can review the code and merge to the website.

**Comment by Decentricity** [comment]
@danwchan my colleague @gilangbh has already created a pull request for Degenics -- do you see it?

**Comment by danwchan** [comment]
Yes I believe I merged it as #289. So you should be all good then, sorry for any confusion.
