### ISSUE TITLE
Genspace page out of date 

### ISSUE THREAD

**Issue by elizabethtuck** [DIYbiosphere/sphere#296]
Please update Genspace description with the following text from our [website](https://www.genspace.org/)

Genspace is the world’s first community biology lab — a place where people of all backgrounds can learn, create, and grow with the life sciences. 

Since 2009, we have served the greater New York area by providing hands-on STEAM education programs for youth and adults, cultural and outreach events for the public, and a membership program to support New York’s community of creatives, researchers, and entrepreneurs. Our programs demystify scientific processes, provide a platform for innovation, and cultivate the next generation of life sciences leaders in emerging global technologies, such as biotechnology, neuroscience, epidemiology, genomics, and many more. 

Please update "status" to Active 

And please update [logo](https://images.squarespace-cdn.com/content/588b7cc315d5dbdea1425e5e/1570552144192-LKZBXTCCBNBD5IE3NRVM/a1.png?format=1500w&content-type=image%2Fpng)

**Comment by 100ideas** [comment]
gonna close this in favor of #290
