### ISSUE TITLE
Implement omnibar functionality

### ISSUE THREAD

**Issue by cube5** [DIYbiosphere/sphere#31]
The header search bar is intended to be an omnibar :mag: where the user can search for text in the whole site.

**Comment by cube5** [comment]
Now you can perform a full text search from the header input :grin:  :

![image](https://cloud.githubusercontent.com/assets/12036916/15831313/9df15b56-2be2-11e6-9d1f-30bc35aaa840.png)

**Comment by cube5** [comment]
Consider change current implementation to Google's search

**Comment by ahuacatl** [comment]
There is only one issue.. I don't know why in the search results it shows the icon in some results and not in others.
![screen shot 2016-07-13 at 13 48 15](https://cloud.githubusercontent.com/assets/18292357/16802350/9960d1d0-4900-11e6-8e70-234c8f950000.png)

**Comment by ahuacatl** [comment]
I just found another issue. It seems as if the search function is not really working... See this GIF, when trying to search for an entry in Eindhoven... 
![omni search](https://cloud.githubusercontent.com/assets/18292357/16803639/c3e5ff6e-4907-11e6-9344-3da71a04f8a4.gif)

**Comment by ahuacatl** [comment]
I found a plugin for searching: [lunr.js](http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/). Don't know if it's useful

**Comment by ahuacatl** [comment]
Algolia also has a free search engine for documentation: [DocSearch](https://community.algolia.com/docsearch/)

**Comment by ahuacatl** [comment]
Here is another one called [Searchbox](http://shipow.github.io/searchbox/)

**Comment by ahuacatl** [comment]
Maybe not completely related to this issue but [Algolia Places](https://community.algolia.com/places/) Also looks like an excellent option!

**Comment by sabgaby** [comment]
Here is another option with [elastic search](https://botleg.com/stories/implement-elasticsearch-in-jekyll-blog/)

**Comment by sabgaby** [comment]
And [tapir](http://tapirgo.com/)

**Comment by ahuacatl** [comment]
Algolia ma offer a [free plan](https://www.algolia.com/doc/faq/accounts-billing/i-develop-an-open-source-or-not-for-profit-project) for open-source and non-profit projects.. 
![screen shot 2016-08-29 at 07 16 30](https://cloud.githubusercontent.com/assets/18292357/18041404/b29f63d2-6db8-11e6-8e7b-70d8d2f8f655.png)

**Comment by ahuacatl** [comment]
The omnisearch idea has been scratched. DocSearch has been implemented for searching the documentation #141, and Algolia jekyll plugin will be added to search the database.
