### ISSUE TITLE
Specify contributing guidelines

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#37]
The CONTRIBUTING file is what contributors would see in order to contribute to the project. It has to be very complete and link to appropriate resources, and it should be easy to follow

**Comment by kaythaney** [comment]
Some resources!

* How to build a contributing.md: https://mozillascience.github.io/working-open-workshop/contributing/

* GitHub's guide to setting guidelines for contributors: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by sabgaby** [comment]
This individual issue is about improving documentation. Anyhow, the management of writing pages now belongs to the [DIYbiosphere/talk](https://github.com/DIYbiosphere/talk) repository
