### ISSUE TITLE
Create basic documentation for contributions!

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#39]
There is a lot of missing documentation in order to support contributors and users! We contemplate that many contributors will be completely new to GitHub and maybe Markdown. Therefore tutorials should include as many helpful hints as possible

**Comment by kaythaney** [comment]
@sabgaby @jasonbobe would love your input on this: https://github.com/DIYbiosphere/sphere.dir/blob/master/CONTRIBUTING.md 

(trying to track down where stuff lives, where folks contribute, but a lot of the links just go back to the README.md :) )

**Comment by sabgaby** [comment]
Hey @kaythaney! I know there are a lot of broken links and missing documentation; as you can see it's a an "Epic" Issue on our Project (we use ZenHub to manage our issues; see #36, #37, #38)! I am (almost) the sole contributor to this project, I guessed that if someone from the mozsprint wanted to contribute, or was interested, they could join our [Gitter](https://gitter.im/DIYbiosphere/sphere.dir?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) or our [Slack](https://diybiosphere.herokuapp.com/) to get a better idea of what and how they could contribute.

**Comment by kaythaney** [comment]
you got it! pushed a PR for the README. took a first cut at updating some of the links. more to come!

sent on the move. apologies for typos.

**Comment by sabgaby** [comment]
This individual issue is about improving documentation. Anyhow, the management of writing pages now belongs to the [DIYbiosphere/talk](https://github.com/DIYbiosphere/talk) repository
