### ISSUE TITLE
Mapping entries 

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#65]
We want to be able to map the entries.
Possible software includes:
[CartoDB](https://cartodb.com/)
[MapBox](https://www.mapbox.com/)
[Leaflet](http://leafletjs.com/index.html)

Additional visualization software:
[D3](https://d3js.org/)

**Comment by 100ideas** [comment]
I suggest mapzen api supposedly biggest open-data geocoding https://mapzen.com/products/search/

**Comment by sabgaby** [comment]
duplicated issue. Refer to #64
