### ISSUE TITLE
Suggestions of Jekyll Plugins

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#66]
I went through the list of jekyll plugins and I am attaching each to a comment so they can be voted on!

**Comment by sabgaby** [comment]
### [Jekyll-tagging](http://www.jekyll-plugins.com/plugins/jekyll-tagging)
Jekyll plugin to automatically generate a tag cloud and tag pages.

**Comment by sabgaby** [comment]
### [Related Posts](http://www.jekyll-plugins.com/plugins/related_posts-jekyll_plugin)
Replaces jekyll's related_posts function to use tags to calculate relationships

**Comment by sabgaby** [comment]
### [Simple-Jekyll-Search](http://www.jekyll-plugins.com/plugins/simple-jekyll-search)
A JavaScript library to add search functionality to any Jekyll blog.

**Comment by ahuacatl** [comment]
### [Markdown References](https://github.com/olov/jekyll-references)
Add references.rb file to your _plugins directory (create it if needed). Create a file named _references.md in your Jekyll site root, then add your markdown reference-style link definitions to it.

**Comment by ahuacatl** [comment]
### [Deprecated Articles](https://github.com/kzykbys/JekyllPlugins)

deprecating_keeper.rb is a simple Jekyll filter which monitor how old an article is. Some articles like about third party API, library etc. can be valid for certain terms. This code fragment will render 'This article might be too old.' after 6 months.

**Comment by ahuacatl** [comment]
### [OEmbed Liquid Tag for Jekyll](https://gist.github.com/vanto/1455726)


This is a simple liquid tag that helps to easily embed images, videos or slides from OEmbed enabled providers. It uses Magnus Holm's great oembed gem which connects to the OEmbed endpoint of the link's provider and retrieves the HTML code to embed the content properly (i.e. an in-place YouTube player, Image tag for Flickr, in-place slideshare viewer etc.).

**Comment by ahuacatl** [comment]
### [Jekyll Gallery Tag](https://github.com/mattvh/JekyllGalleryTag)

Jekyll plugin to generate thumbnails from a directory of images and display them with a Liquid tag

**Comment by ahuacatl** [comment]
### [FontAwesome Icon Liquid Tag](https://gist.github.com/23maverick23/8532525)

An include tag for FontAwesome icons

**Comment by ahuacatl** [comment]
### [Jekyll Figure](https://github.com/lmullen/jekyll_figure)

Adds a Liquid figure tag to a Jekyll site

**Comment by ahuacatl** [comment]
### [GitHub Sample Tag](https://github.com/bwillis/jekyll-github-sample)

Two Jekyll Liquid tags to display a code sample from a file in a public Github repo and provide a reference to it.

**Comment by ahuacatl** [comment]
### [Liquid Gist Tag for Jekyll](http://blog.55minutes.com/2012/03/liquid-gist-tag-for-jekyll/)

Liquid tags to render gists

**Comment by ahuacatl** [comment]
### [Jekyll Maps](https://ayastreb.me/jekyll-maps/#examples)

Easily embed GoogleMaps with locations from your Jekyll posts or data files.

**Comment by ahuacatl** [comment]
### [Jekyll Tagging Related Posts](https://github.com/toshimaru/jekyll-tagging-related_posts)

Jekyll related_posts function based on tags (works on Jekyll3). It replaces original Jekyll's related_posts function to use tags to calculate relationships.

**Comment by ahuacatl** [comment]
### [Jekyll Remote Include](http://www.northfieldx.co.uk/remote-include/)

It’s like {% include file.html %} but instead of grabbing files from your _includes directory it gets the file from a remote URL.

**Comment by sabgaby** [comment]
### [Jekyll Admin](https://github.com/jekyll/jekyll-admin)

A Jekyll plugin that provides users with a traditional CMS-style graphical interface to author content and administer Jekyll sites.

**Comment by sabgaby** [comment]
### [Jekyll Gallery Generator](https://github.com/ggreer/jekyll-gallery-generator)
A Jekyll plugin that generates photo galleries from directories full of images.

**Comment by sabgaby** [comment]
### [Jekyll Thumbnailer](https://github.com/mrdanadams/jekyll-thumbnailer)
Image thumbnailing plugin for Jekyll / octopress

**Comment by sabgaby** [comment]
### [Jekyll Get](https://github.com/18F/jekyll-get)
Jekyll plugin to download data from external JSON sources to use in generating a site

**Comment by sabgaby** [comment]
### [Jekyll Flickr Set Tag](https://github.com/tsmango/jekyll_flickr_set_tag)
A Jekyll plugin for generating image galleries from Flickr sets.

**Comment by sabgaby** [comment]
### [Jekyll Auto Image](https://github.com/merlos/jekyll-auto-image)
jekyll plugin that makes available the first image of a post in the template

**Comment by sabgaby** [comment]
### [Jekyll Directory](https://github.com/sillylogger/jekyll-directory)
a jekyll plugin for exposing a directory's files

**Comment by sabgaby** [comment]
### [Gekyll](https://github.com/jsvine/gekyll)
Gekyll is a Jekyll plugin that lets you use Git repositories as posts, giving you access to a post's commits, diffs, and more.

**Comment by sabgaby** [comment]
### [Jekyll Page Collections](https://github.com/jeffkole/jekyll-page-collections)
Jekyll plugin to manage collections of pages just like posts

**Comment by sabgaby** [comment]
### [Jekyll Pages Api](https://github.com/18F/jekyll_pages_api)
a Jekyll Plugin that generates a JSON file with data for all the Pages in your Site

**Comment by sabgaby** [comment]
### [Jekyll TOC](https://github.com/toshimaru/jekyll-toc)
A liquid filter plugin for Jekyll which generates a table of contents.

**Comment by sabgaby** [comment]
### [Instagram Jekyll](https://github.com/mthomas/instagram-jekyll)
Jekyll plugin to display Instagram photos.

**Comment by sabgaby** [comment]
### [Jekyll Figure Image Tag](https://github.com/opattison/jekyll-figure-image-tag)
Image Jekyll plugin for generating figure/image/caption HTML content

**Comment by sabgaby** [comment]
### [Jekyll YAML block](https://github.com/dalenys/jekyll-yaml-block)
🔻 Jekyll plugins to capture YAML sections in a variable.

**Comment by sabgaby** [comment]
### [Jekyll Type Filter](https://github.com/dalenys/jekyll-type-filter)
🔻 Jekyll plugins to check variable type.

**Comment by sabgaby** [comment]
### [Jekyll RSS absolute URLs](https://github.com/jessecrouch/jekyll-rss-absolute-urls)
A Jekyll plugin that converts relative URLs to absolute ones in href and src attributes. Designed for RSS feeds.

**Comment by sabgaby** [comment]
### [Jekyll Site Menus](https://github.com/Painted-Fox/jekyll-site-menus)
This jekyll plugin enables enables you to define site menues within your `_config.yml` file.

**Comment by sabgaby** [comment]
### [Jekyll Version Plugin](https://github.com/rob-murray/jekyll-version-plugin)
A Liquid tag plugin for Jekyll that renders a version identifier for your Jekyll site, sourced from the git repository.

**Comment by sabgaby** [comment]
### [Jekyll Avatar](https://github.com/benbalter/jekyll-avatar)
A Jekyll plugin for rendering GitHub avatars

**Comment by sabgaby** [comment]
### [Jekyll Footnotes](https://github.com/orangejulius/jekyll-footnotes)
A Jekyll plugin for footnotes

**Comment by sabgaby** [comment]
### [Jekyll Include Absolute Plugin](https://github.com/tnhu/jekyll-include-absolute-plugin)
A liquid tag to include a file from its path relate to Jekyll's source folder

**Comment by sabgaby** [comment]
### [Jekyll Remote Markdown](https://github.com/Rolinh/jekyll-remote-markdown)
Jekyll plugin to deal with remote markdown files.

**Comment by sabgaby** [comment]
### [Jekyll Giphy](https://github.com/vfalanis/jekyll-giphy)
Plugin for adding Giphy GIFS on Jekyll sites http://vfalanis.me/giphy/

**Comment by 100ideas** [comment]
closing since it's so old
