### ISSUE TITLE
Advanced Search and Filter

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#71]
The button in the landing page.. maybe the same one when displaying the list of initiatives... 
Here is GIF of how the search and select function works in google sheets, and a copy of the design artboards 
![advanced search](https://cloud.githubusercontent.com/assets/5911330/15895543/22c443ac-2d8c-11e6-8a61-c6daf1930dd2.png)
![dropdown search](https://cloud.githubusercontent.com/assets/5911330/15895542/22c1af70-2d8c-11e6-816e-f0ee8969d8f9.png)
![advanced search](https://cloud.githubusercontent.com/assets/5911330/15895555/2ad186b8-2d8c-11e6-915e-3b3f4591b8a1.gif)

**Comment by ahuacatl** [comment]
has the coding been done to distinguish between active and non-active initiatives?
Basically... it should be something like in the front matter
```
---
since: 2012
---
```
this is equal to active. if
```
---
since: 2012-2014
---
```
then it should be as inactive

**Comment by sabgaby** [comment]
The search function will be performed by Algolia, it searched name and location (country and city). It displays the logo of the initiative if there is one. But other functionalities are still missing
