### ISSUE TITLE
If statements not working in infobox

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#77]
In entry.html, there are if statements that determine wether the certain fields will show or not.. this is not working. 
![screen shot 2016-06-13 at 23 15 35](https://cloud.githubusercontent.com/assets/5911330/16037894/d6a632f0-3222-11e6-904b-6b36c76123af.png)

**Comment by cube5** [comment]
Yep, bad syntax :sweat_smile: let me fix it

**Comment by ahuacatl** [comment]
Commas are still showing when the fields are left empty.. maybe the code has to specify that to only show the icon and commas if the field in the front matter is not null

![screen shot 2016-07-13 at 14 19 51](https://cloud.githubusercontent.com/assets/18292357/16803123/e9e3b2ae-4904-11e6-906a-5473cdbc05da.png)
