### ISSUE TITLE
Image aligment in Markdown

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#86]
For example, in an Entry for a Lab, they list their Projects, and these should have a nice photo to make it more pretty. It would be nice to format that image square and floating left. like in the artboard below.
![screen shot 2016-06-15 at 00 32 23](https://cloud.githubusercontent.com/assets/5911330/16061972/ae46789c-3290-11e6-82d3-0c353645e85f.png)

A possible solution I found is [here](http://stackoverflow.com/a/16278366) and [here] explained a bit more https://thornelabs.net/2014/11/30/centering-images-with-jekyll-and-markdown.html but it exactly same idea

**Comment by cube5** [comment]
We can take different approaches here, I was able to set use a two column layout [using html inside the markdown file][1]. I think it is the simpliest way:


```
<!-- first column (for the image) -->
<div class="col-sm-3" markdown="1">
<!-- project image -->
![Logo](http://placehold.it/180x171){: .img-responsive }
</div>

<!-- second column (for the description) -->
<div class="col-sm-9" markdown="1">
<!-- project description -->
### DIYbiosphere
Here goes the content Here goes the content Here goes the content Here goes the content Here goes
the content Here goes the content Here goes the content Here goes the content Here goes the content 
Here goes the content Here goes the content Here goes the content Here goes the content Here goes 
the content Here goes the content Here goes the content Here goes the content Here goes the content 
Here goes the content.
</div>
```

results into something like this:
![image](https://cloud.githubusercontent.com/assets/12036916/16309127/459f02b6-392d-11e6-8051-41fe8516001c.png)


please let me know your thoughts

[1]: https://github.com/planetjekyll/quickrefs/blob/master/FAQ.md#user-content-q-jekyll-doesnt-render-markdown-when-adding-html-tags

**Comment by sabgaby** [comment]
I would vote against using html code.. I would rather then use an include or something similar... learning markdown is easy... and the jekyll's include are not as ugly as html, IMO

**Comment by sabgaby** [comment]
This should be resolved much easily with Semantic UI. hooray!
