### ISSUE TITLE
Can we use page.content from other sites?

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#94]
I was thinking if it would be possible to show the {{ page.content }} of different pages which I can specify: say:

```
{{ page1.content }}

this is text in the markdown or html site

{{ page2.content }}

```

I found the following resources but I don't know if they will work
- [Markdown vs include plugin](http://wolfslittlestore.be/2013/10/rendering-markdown-in-jekyll/)
- [Capture section](https://github.com/jekyll/jekyll/issues/246)
- [SitePage](http://stackoverflow.com/questions/32022515/call-a-specific-page-variable-in-jekyll)

**Comment by 100ideas** [comment]
closing since it's so old - will revisit
