### ISSUE TITLE
Style external links

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#98]
In the text, it would be nice to have a visible style to signal whether the link is internal or external. 
I found a [jQuery](http://www.dotnetcurry.com/ShowArticle.aspx?ID=633) that does this
[JavaScript](http://www.learningjquery.com/2008/08/quick-tip-dynamically-add-an-icon-for-external-links) is another option, in this link they also detail CSS. This is another [CSS](http://askthecssguy.com/articles/showing-hyperlink-cues-with-css/). Another [Java](http://stackoverflow.com/questions/27089500/jekyll-produce-custom-html-for-external-links-target-and-css-class) code

**Comment by ahuacatl** [comment]
Done!
